# Generated by Django 3.2.8 on 2021-10-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211007_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='type',
        ),
    ]
