# Generated by Django 3.2.7 on 2021-10-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_name_class_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=450)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique', to='main_app.gyms')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
